### ISSUE TITLE
instruction for using this with  vc707 Evaluation board  

### ISSUE THREAD

**Issue by JackAhm** [IamVNIE/V7_ETHERNET#1]
Hello thanks for this IP Core but the instruction file is for ML507. could please tell us the different  . 
and how we can change the address of it cause it says we should a specific address .
thanks in advance

**Comment by IamVNIE** [comment]
You need to refer Page 12 of this document to get the right switch settings for VC707. https://www.xilinx.com/support/documentation/boards_and_kits/virtex-7/vc707-ethernet-pdf-xtp148-14.3.pdf

**Comment by JackAhm** [comment]
thank you . it works
